# https://travis-ci.org/conda/constructor

language: python
sudo: false

branches:
  only:
    - master

env:
  global:
    - CONSTRUCTOR_CACHE=/tmp/constructor_travis_ci

matrix:
  include:
    # Linux
    - os: linux
      language: generic
      env: PYTHON_VERSION=3.6 CONDA_VERSION=4.6
    - os: linux
      language: generic
      env: PYTHON_VERSION=2.7 CONDA_CANARY=true
    - os: linux
      language: generic
      env: PYTHON_VERSION=3.7 CONDA_CANARY=true
    # OSX
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.6 CONDA_VERSION=4.7
    # Linux on power
    - os: linux
      language: generic
      env: PYTHON_VERSION=3.6 CONDA_VERSION=4.6
      arch: ppc64le
    - os: linux
      language: generic
      env: PYTHON_VERSION=2.7 CONDA_CANARY=true
      arch: ppc64le
    - os: linux
      language: generic
      env: PYTHON_VERSION=3.7 CONDA_CANARY=true
      arch: ppc64le
  allow_failures:
    - os: linux
      language: generic
      env: PYTHON_VERSION=3.7 CONDA_CANARY=true
    - os: linux
      language: generic
      env: PYTHON_VERSION=2.7 CONDA_CANARY=true
    - os: linux
      language: generic
      env: PYTHON_VERSION=3.7 CONDA_CANARY=true
      arch: ppc64le
    - os: linux
      language: generic
      env: PYTHON_VERSION=2.7 CONDA_CANARY=true
      arch: ppc64le

cache:
  directories:
    - $HOME/condacache/pkgs
    - $HOME/.cache/pip

install:
  - mkdir -p $HOME/condacache/pkgs
  # Install latest miniconda
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://repo.anaconda.com/pkgs/misc/conda-execs/conda-latest-linux-64.exe -O conda.exe;
    else
      wget https://repo.anaconda.com/pkgs/misc/conda-execs/conda-latest-osx-64.exe -O conda.exe;
    fi
  - chmod +x conda.exe

  - export CONDA_PKGS_DIRS="~/condacache/pkgs"
  - export CONDA_ALWAYS_YES="true"
  - export CONDA_AUTO_UPDATE_CONDA="false"

  - if [ "${CONDA_CANARY}" = "true" ]; then
      ./conda.exe create -y -q -p ~/miniconda -c conda-canary conda python=$PYTHON_VERSION;
    else
      ./conda.exe create -y -q -p ~/miniconda -c conda-canary conda=$CONDA_VERSION python=$PYTHON_VERSION;
    fi
  - ./conda.exe install -y -p ~/miniconda pillow>=3.1 ruamel_yaml conda-forge::codecov pytest pytest-cov
  - source "$HOME"/miniconda/bin/activate
  # Install this package
  - python setup.py develop

  # this needs
  - mkdir $HOME/miniconda/standalone_conda
  - cp conda.exe $HOME/miniconda/standalone_conda/conda.exe

  # diagnostics
  - conda info
  - conda init
  - source "$HOME"/miniconda/bin/activate
  - conda list

script:
  - pytest --cov=constructor constructor
  - python scripts/run_examples.py

after_success:
  - codecov
